[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "humble"
extra-package-mappings = [
	{ file = "./mapping.yaml" }
]

[package.host-dependencies]
ros-humble-my-dep-pkg = { path = "../my_dep_pkg" }

[package.build-dependencies]
ros-humble-my-dep-pkg = { path = "../my_dep_pkg" }

[package.run-dependencies]
ros-humble-my-dep-pkg = { path = "../my_dep_pkg" }
