[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "humble"
extra-package-mappings = [
	{ mapping.localpackages.my_dep_pkg = ["ros-humble-my-dep-pkg"] }
]
